### ISSUE TITLE
dockerfile run error erigon 

### ISSUE THREAD

**Issue by holiman** [holiman/goevmlab#145]
```
erigon error: invalid character 'p' looking for beginning of value
  | panic: interface conversion: *mdbx.MdbxTx is not kv.TemporalGetter: missing method DomainGet
  | 
  | goroutine 1 [running]:
  | github.com/ledgerwatch/erigon/turbo/rpchelper.NewLatestStateReader(...)
  |     github.com/ledgerwatch/erigon/turbo/rpchelper/helper.go:150
  | github.com/ledgerwatch/erigon/tests.MakePreState(0xc00149ec88, {0x1bd82b0, 0xc000c7f140}, 0xc000c7d3b0, 0x1, 0x1)
  |     github.com/ledgerwatch/erigon/tests/state_test_util.go:330 +0xc34
  | github.com/ledgerwatch/erigon/tests.(*StateTest).RunNoVerify(0xc00149f1d0, {0x1bd82b0, 0xc000c7f140}, {{0xc0013fb796?, 0x27bd820?}, 0xc00149eec0?}, {0x1, {0x1bc6f78, 0xc0014b50c8}, 0x0, ...})
  |     github.com/ledgerwatch/erigon/tests/state_test_util.go:197 +0x205
  | github.com/ledgerwatch/erigon/tests.(*StateTest).Run(0xc00149f1d0, {0x1bd82b0?, 0xc000c7f140?}, {{0xc0013fb796?, 0x1000?}, 0x0?}, {0x1, {0x1bc6f78, 0xc0014b50c8}, 0x0, ...})
  |     github.com/ledgerwatch/erigon/tests/state_test_util.go:166 +0x8d
  | main.aggregateResultsFromStateTests(0xc000c7c4e0, {0x1, {0x1bc6f78, 0xc0014b50c8}, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
  |     github.com/ledgerwatch/erigon/cmd/evm/staterunner.go:152 +0x7ad
  | main.runStateTest({0xc000c94c20?, 0x0?}, {0x1, {0x1bc6f78, 0xc0014b50c8}, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
  |     github.com/ledgerwatch/erigon/cmd/evm/staterunner.go:112 +0xbe
  | main.stateTestCmd(0xc000c9b8c0)
  |     github.com/ledgerwatch/erigon/cmd/evm/staterunner.go:92 +0x6d7
  | github.com/urfave/cli/v2.(*Command).Run(0x26e9900, 0xc000c9b8c0, {0xc0009e4e60, 0x1, 0x1})
  |     github.com/urfave/cli/v2@v2.27.2/command.go:276 +0x97d
  | github.com/urfave/cli/v2.(*Command).Run(0xc0003454a0, 0xc000c9b180, {0xc0002ba000, 0x5, 0x5})
  |     github.com/urfave/cli/v2@v2.27.2/command.go:269 +0xbb7
  | github.com/urfave/cli/v2.(*App).RunContext(0xc000003000, {0x1bbf5e0, 0x2828de0}, {0xc0002ba000, 0x5, 0x5})
  |     github.com/urfave/cli/v2@v2.27.2/app.go:333 +0x58b
  | github.com/urfave/cli/v2.(*App).Run(...)
  |     github.com/urfave/cli/v2@v2.27.2/app.go:307
  | main.main()
  |     github.com/ledgerwatch/erigon/cmd/evm/main.go:193 +0x45

```

**Comment by holiman** [comment]
tracked in https://github.com/ledgerwatch/erigon/issues/10298
