### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mainnet.infura.io/remix

### ISSUE THREAD

**Issue by dipanjan** [holiman/goevmlab#35]
While trying out the example in the README inside the docker image provided, I am receiving the following error:

```
# python3 utilities/opviewer.py --hash 0x9dbf0326a03a2a3719c27be4fa69aacc9857fd231a8d9dcaede4bb083def75ec -g /evm --no-docker

Traceback (most recent call last):
  File "utilities/opviewer.py", line 13, in <module>
    opviewer.main()
  File "/usr/lib/python3.6/site-packages/evmlab/tools/opviewer.py", line 1061, in main
    trace.reproduce(tx=args.hash, vm=vm)
  File "/usr/lib/python3.6/site-packages/evmlab/tools/opviewer.py", line 832, in reproduce
    artefacts, vm_args = reproduce.reproduceTx(tx, vm, self.api)
  File "/usr/lib/python3.6/site-packages/evmlab/reproduce.py", line 122, in reproduceTx
    tx = api.getTransaction(txhash)
  File "/usr/lib/python3.6/site-packages/evmlab/multiapi.py", line 77, in getTransaction
    obj = self.web3.eth.getTransaction(h)
  File "/usr/lib/python3.6/site-packages/web3/eth.py", line 196, in getTransaction
    [transaction_hash],
  File "/usr/lib/python3.6/site-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/usr/lib/python3.6/site-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.6/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/usr/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/lib/python3.6/site-packages/web3/middleware/exception_retry_request.py", line 80, in middleware
    return make_request(method, params)
  File "/usr/lib/python3.6/site-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/usr/lib/python3.6/site-packages/web3/utils/request.py", line 27, in make_post_request
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mainnet.infura.io/remix
```

**Comment by holiman** [comment]
This repository is deprecated (I should archive it), we're using https://github.com/holiman/goevmlab now, it's basically the same thing rewritten in go

**Comment by holiman** [comment]
Ah, my bad, I thought you were commenting on the old repo, but actually, this is the new one. 
` python3 utilities/opviewer.py` -- that's not something which exists in this repository. Where did you see a reference to that ?

**Comment by dipanjan** [comment]
I found the reference to the docker image on the [EVM Tracing](https://geth.ethereum.org/docs/dapp/tracing) page.

```
docker pull holiman/evmlab && docker run -it holiman/evmlab
```

`utilities/opviewer.py` is available inside the docker image.

**Comment by holiman** [comment]
I see, that's confusing. I've made a PR to remove it: https://github.com/ethereum/go-ethereum/pull/23042
