### ISSUE TITLE
tracediff nethermind error

### ISSUE THREAD

**Issue by MariusVanDerWijden** [holiman/goevmlab#37]
Test: https://gist.github.com/MariusVanDerWijden/f5fc11a972da46d4142b3a30bc36787a

```
~/goevmlab/cmd/tracediff/tracediff geth4 neth4                                                                                                                
panic: interface conversion: interface {} is string, not float64

goroutine 1 [running]:
github.com/holiman/goevmlab/traces.convertToStructLog(0xc0004547b0, 0x7e, 0x80, 0x664de0)
        /root/goevmlab/traces/reader.go:134 +0x87f
github.com/holiman/goevmlab/traces.readJsonLines(0x6fd080, 0xc000454240, 0xc2e02, 0x0, 0x6fd100)
        /root/goevmlab/traces/reader.go:307 +0x1dd
github.com/holiman/goevmlab/traces.ReadFile(0x7fffa9c3278b, 0x5, 0xc00011b710, 0x0, 0x0)
        /root/goevmlab/traces/reader.go:352 +0x18f
main.main()
        /root/goevmlab/cmd/tracediff/main.go:69 +0x2b0
```

**Comment by holiman** [comment]
This works for me now, seems fixed
